name: Etl flow

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run wf1
        run: python wf1.py

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run wf2
        run: python wf2.py

  job3:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run wf3
        run: python wf3.py

  job4:
    needs: job2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run wf4
        run: python wf4.py

  job5:
    needs: job3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run wf5
        run: python wf5.py

  job6:
    needs: [job4, job5]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run wf6
        run: python wf6.py
